// elect/runoob/19-vue-electron/App.vue
<template>
<div>
  <h1>笔记列表</h1>
  <button @click="openNoteWindow">新建笔记</button>
  <ul>
    <li v-for="(note, index) in notes" :key="index">{{ note }}</li>
  </ul>
</div>
</template>

<script>
export default {
  data() {
    return { notes: [] }
  },
  methods: {
    openNoteWindow() {
      window.open('note.html', '新建笔记', 'width=400,height=300')
    }
  },
  mounted() {
    window.electronAPI.getNotes().then((notes) => {
      this.notes = notes
    })
    window.electronAPI.onUpdateNotes((event, notes) => {
      this.notes = notes
    })
  }
}
</script>

// elect/runoob/18-react-electron/App.js
import React, { useState, useEffect } from 'react'

function App() {
  const [notes, setNotes] = useState([])

  useEffect(() => {
    window.electronAPI.getNotes().then(setNotes)
    window.electronAPI.onUpdateNotes((_event, newNotes) => setNotes(newNotes))
  }, [])

  const openNoteWindow = () => {
    window.open('note.html', '新建笔记', 'width=400,height=300')
  }

  return (
    <div style={{ padding: 20 }}>
      <h1>我的笔记</h1>
      <button onClick={openNoteWindow}>新建笔记</button>
      <ul>
        {notes.map((n, i) => (
          <li key={i}>{n}</li>
        ))}
      </ul>
    </div>
  )
}

export default App
